#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# AfterInstall hook — installs Python deps and writes the env file.
# Runs as root.
# ──────────────────────────────────────────────────────────────
set -euo pipefail
exec > >(tee -a /var/log/pfa-deploy.log) 2>&1

echo "[after-install] Starting at $(date -Iseconds)"

STAGE="${STAGE:-dev}"
# Use IMDSv2 token — required when instance metadata requires token auth
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
REGION=$(curl -s -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" \
  "http://169.254.169.254/latest/meta-data/placement/region")

# ── Install Python dependencies ───────────────────────────────
echo "[after-install] Installing Python dependencies"
cd /opt/pfa
python3.12 -m pip install -e . --quiet

# ── Fetch secrets from AWS ────────────────────────────────────
echo "[after-install] Fetching secrets from Secrets Manager and SSM"

# DB credentials (JSON blob)
DB_SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "pfa/db/${STAGE}" \
  --region "${REGION}" \
  --query SecretString --output text)

DB_HOST=$(echo "${DB_SECRET_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('host','localhost'))")
DB_PORT=$(echo "${DB_SECRET_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('port',5432))")
DB_USER=$(echo "${DB_SECRET_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('username','pfa_user'))")
DB_PASS=$(echo "${DB_SECRET_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('password',''))")

# SSM parameters helper
fetch_ssm() {
  aws ssm get-parameter \
    --name "/pfa/${STAGE}/$1" \
    --with-decryption \
    --region "${REGION}" \
    --query Parameter.Value --output text 2>/dev/null || echo ""
}

JWT_SECRET=$(fetch_ssm "jwt-secret")
JWT_REFRESH_SECRET=$(fetch_ssm "jwt-refresh-secret")
STRIPE_SECRET_KEY=$(fetch_ssm "stripe-secret-key")
STRIPE_WEBHOOK_SECRET=$(fetch_ssm "stripe-webhook-secret")
STRIPE_PRICE_ID=$(fetch_ssm "stripe-price-id")
SES_SENDER_EMAIL=$(fetch_ssm "ses-sender-email")
OPENAI_API_KEY=$(fetch_ssm "openai-api-key")
DOMAIN_NAME=$(fetch_ssm "domain-name")

# SQS queue URLs from SSM (stored by data-stack CDK)
SQS_STATEMENT_UPLOADED=$(fetch_ssm "sqs/statement-uploaded-url")
SQS_STATEMENT_PARSED=$(fetch_ssm "sqs/statement-parsed-url")
SQS_TRANSACTIONS_CATEGORIZED=$(fetch_ssm "sqs/transactions-categorized-url")
SQS_ANOMALIES_DETECTED=$(fetch_ssm "sqs/anomalies-detected-url")
SQS_REPORT_SCHEDULE=$(fetch_ssm "sqs/report-schedule-url")
SQS_REPORT_GENERATED=$(fetch_ssm "sqs/report-generated-url")
SQS_SUBSCRIPTION_EVENTS=$(fetch_ssm "sqs/subscription-events-url")

FRONTEND_URL="https://${DOMAIN_NAME:-placeholder.example.com}"

# ── Write environment file ────────────────────────────────────
echo "[after-install] Writing /etc/pfa/env"
cat > /etc/pfa/env << EOF
# Auto-generated by CodeDeploy after-install hook
# DO NOT EDIT MANUALLY — re-run deployment to update

ENVIRONMENT=${STAGE}
DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/pfa_db
JWT_SECRET_KEY=${JWT_SECRET}
JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET}

AWS_DEFAULT_REGION=${REGION}
S3_STATEMENTS_BUCKET=pfa-statements-${STAGE}
S3_REPORTS_BUCKET=pfa-reports-${STAGE}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_PREMIUM_PRICE_ID=${STRIPE_PRICE_ID}

SES_SENDER_EMAIL=${SES_SENDER_EMAIL}
SES_SENDER_NAME=AI Finance Analyzer

OPENAI_API_KEY=${OPENAI_API_KEY}

SQS_STATEMENT_UPLOADED_URL=${SQS_STATEMENT_UPLOADED}
SQS_STATEMENT_PARSED_URL=${SQS_STATEMENT_PARSED}
SQS_TRANSACTIONS_CATEGORIZED_URL=${SQS_TRANSACTIONS_CATEGORIZED}
SQS_ANOMALIES_DETECTED_URL=${SQS_ANOMALIES_DETECTED}
SQS_REPORT_SCHEDULE_URL=${SQS_REPORT_SCHEDULE}
SQS_REPORT_GENERATED_URL=${SQS_REPORT_GENERATED}
SQS_SUBSCRIPTION_EVENTS_URL=${SQS_SUBSCRIPTION_EVENTS}

FRONTEND_URL=${FRONTEND_URL}
EOF

chmod 640 /etc/pfa/env
chown root:pfa /etc/pfa/env

# ── Install systemd service ───────────────────────────────────
echo "[after-install] Installing pfa-api systemd service"
cp /opt/pfa/pfa-api.service /etc/systemd/system/pfa-api.service
systemctl daemon-reload
systemctl enable pfa-api

echo "[after-install] Complete"
